
//import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Demian
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    ImageIcon Icono = new ImageIcon("imagenes/Imagen_Icono.png");
    public Modificar() {
        initComponents();
        setIconImage(getIconImage());
    }
     @Override
    public Image getIconImage (){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Imagen_icono.png"));
        return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNA = new javax.swing.JTextField();
        txtNuE = new javax.swing.JTextField();
        txtNP = new javax.swing.JTextField();
        txtNE = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblNL = new javax.swing.JLabel();
        lblNA = new javax.swing.JLabel();
        lblNE = new javax.swing.JLabel();
        lblNP = new javax.swing.JLabel();
        lblNuE = new javax.swing.JLabel();
        lblAP = new javax.swing.JLabel();
        txtNL = new javax.swing.JTextField();
        cbxNL = new javax.swing.JCheckBox();
        cbxNA = new javax.swing.JCheckBox();
        cbxNE = new javax.swing.JCheckBox();
        cbxNP = new javax.swing.JCheckBox();
        cbxAP = new javax.swing.JCheckBox();
        cbxNuE = new javax.swing.JCheckBox();
        lblNumero_libro = new javax.swing.JLabel();
        txtNuL = new javax.swing.JTextField();
        btnMPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lblTitulo.setText("Modificación de libros");

        lblNL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNL.setText("Nombre del libro:");

        lblNA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNA.setText("Nombre del autor:");

        lblNE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNE.setText("Nombre de la editorial:");

        lblNP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNP.setText("Numero de páginas:");

        lblNuE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNuE.setText("Numero de editorial:");

        lblAP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAP.setText("Año de publicación:");

        cbxNL.setText("Modificar");

        cbxNA.setText("Modificar");

        cbxNE.setText("Modificar");

        cbxNP.setText("Modificar");

        cbxAP.setText("Modificar");

        cbxNuE.setText("Modificar");

        lblNumero_libro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero_libro.setText("Numero de libro:");

        btnMPrincipal.setText("Volver al inicio");
        btnMPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumero_libro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuL))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNA))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNL, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNuE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNL)
                            .addComponent(cbxNA)
                            .addComponent(cbxNE)
                            .addComponent(cbxNP)
                            .addComponent(cbxAP)
                            .addComponent(cbxNuE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnMPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNL)
                    .addComponent(txtNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNA)
                    .addComponent(txtNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNE)
                    .addComponent(txtNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNP)
                    .addComponent(txtNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAP)
                    .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuE)
                    .addComponent(txtNuE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNuE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero_libro)
                    .addComponent(txtNuL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      
        
        
        
        
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPrincipalActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMPrincipal;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox cbxAP;
    private javax.swing.JCheckBox cbxNA;
    private javax.swing.JCheckBox cbxNE;
    private javax.swing.JCheckBox cbxNL;
    private javax.swing.JCheckBox cbxNP;
    private javax.swing.JCheckBox cbxNuE;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblNA;
    private javax.swing.JLabel lblNE;
    private javax.swing.JLabel lblNL;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblNuE;
    private javax.swing.JLabel lblNumero_libro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtNA;
    private javax.swing.JTextField txtNE;
    private javax.swing.JTextField txtNL;
    private javax.swing.JTextField txtNP;
    private javax.swing.JTextField txtNuE;
    private javax.swing.JTextField txtNuL;
    // End of variables declaration//GEN-END:variables
}
